// <auto-generated />
using System;
using EquipmentBorrowing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EquipmentBorrowing.Infrastructure.Migrations
{
    [DbContext(typeof(EquipmentBorrowingDbContext))]
    [Migration("20261004071028_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("EquipmentBorrowing.Domain.Borrowing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateBorrowed")
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpectedReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("Status");

                    b.HasIndex("StudentId");

                    b.ToTable("Borrowings", (string)null);
                });

            modelBuilder.Entity("EquipmentBorrowing.Domain.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Equipment", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            IsAvailable = true,
                            Name = "Digital Multimeter"
                        },
                        new
                        {
                            Id = 102,
                            IsAvailable = true,
                            Name = "Oscilloscope"
                        },
                        new
                        {
                            Id = 103,
                            IsAvailable = true,
                            Name = "Function Generator"
                        },
                        new
                        {
                            Id = 104,
                            IsAvailable = true,
                            Name = "Soldering Station"
                        },
                        new
                        {
                            Id = 105,
                            IsAvailable = true,
                            Name = "Logic Analyzer"
                        },
                        new
                        {
                            Id = 106,
                            IsAvailable = true,
                            Name = "DC Power Supply"
                        },
                        new
                        {
                            Id = 107,
                            IsAvailable = true,
                            Name = "Breadboard Kit"
                        },
                        new
                        {
                            Id = 108,
                            IsAvailable = true,
                            Name = "Component Tester"
                        });
                });

            modelBuilder.Entity("EquipmentBorrowing.Domain.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAllowedToBorrow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAllowedToBorrow = true,
                            Name = "Alice Santos"
                        },
                        new
                        {
                            Id = 2,
                            IsAllowedToBorrow = true,
                            Name = "Ben Cruz"
                        },
                        new
                        {
                            Id = 3,
                            IsAllowedToBorrow = true,
                            Name = "Carla Reyes"
                        },
                        new
                        {
                            Id = 4,
                            IsAllowedToBorrow = true,
                            Name = "Diego Lim"
                        },
                        new
                        {
                            Id = 5,
                            IsAllowedToBorrow = true,
                            Name = "Eva Tan"
                        });
                });

            modelBuilder.Entity("EquipmentBorrowing.Domain.Borrowing", b =>
                {
                    b.HasOne("EquipmentBorrowing.Domain.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EquipmentBorrowing.Domain.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
